# Generated by Django 5.1.7 on 2025-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False, 'verbose_name': 'Гостиница', 'verbose_name_plural': 'Гостиницы'},
        ),
    ]
