# Generated by Django 5.1.7 on 2025-04-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_hotel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='№ телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('booking_number', models.TextField(verbose_name='Номер бронирования')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
